Repository oracle-samples/oic-rab-vscode, pull requests merged in 2023-12, with the labels that each got.

#9 OIC-48557 notification doesn't disappear on api calls and there are 2 duplication copies
  src/utils.ts
Labels: OCA Verified, patch

#10 Update new xml CNCF function schema
  .gitattributes
  .github/workflows/package.yml
  package-lock.json
  package.json
  schemas/flows_v01.json
Labels: OCA Verified, minor

#11 Update package.yml
  .github/workflows/package.yml
Labels: OCA Verified

#12 FortifyVulnerabilitySolutions: Fix UI Open Redirect
  webview/index.html
  webview/js/libs/index.ecc57c8ece39b7e684b5.js
  webview/js/libs/index.ecc57c8ece39b7e684b5.js.LICENSE.txt
  webview/js/main.8de579bfc07714e25d6a.js
  webview/js/main.ecc57c8ece39b7e684b5.js
  webview/js/runtime.ecc57c8ece39b7e684b5.js
  webview/styles/main.8de579bfc07714e25d6a.css
  webview/styles/main.ecc57c8ece39b7e684b5.css
Labels: OCA Verified
