Repository oracle-samples/oic-rab-vscode, pull requests merged in 2024-04, with the labels that each got.

#36 Validate OpenAPI document
  THIRD_PARTY_LICENSES.txt
  package-lock.json
  package.json
  src/openapi/openapi_v3.0.json
  src/workspace-manager.ts
  tsconfig.json
Labels: OCA Verified, increment patch version

#37 Support import of RAB bundle
  package.json
  src/commands/create-rab-bundle.ts
  src/commands/import-rab-bundle.ts
  src/extension.ts
  src/logger.ts
  src/utils/ui-utils.ts
  src/workspace-manager.ts
Labels: OCA Verified, increment minor version

#38 Sync RAB spec to c2a7af1d0
  schemas/actions_v01.json
  schemas/flows_v01.json
  schemas/info_v01.json
  schemas/mainADD_v01.json
  schemas/schemas_v01.json
  schemas/triggers_v01.json
Labels: OCA Verified, increment minor version

#39 Release v1.1.0 in accordance with OIC24.04
  .vscode/launch.json
  CHANGELOG.md
  README.md
  THIRD_PARTY_LICENSES.txt
  package-lock.json
  package.json
  schemas/actions_v01.json
  schemas/flows_v01.json
  schemas/info_v01.json
  schemas/mainADD_v01.json
  schemas/schemas_v01.json
  schemas/triggers_v01.json
  src/api.ts
  src/commands/convert-add.ts
  src/commands/convert-postman-collection.ts
  src/commands/create-rab-bundle.ts
  src/commands/delete-add.ts
  src/commands/download-rab-bundle.ts
  src/commands/get-add.ts
  src/commands/import-rab-bundle.ts
  src/commands/init-workspace.ts
  src/commands/insert-security-policy.ts
  src/commands/publish-add.ts
  src/commands/register-rab-bundle.ts
  src/commands/remove-rab-bundle.ts
  src/commands/validate-add.ts
  src/commands/version-check.ts
  src/extension.ts
  src/logger.ts
  src/openapi/openapi_v3.0.json
  src/profile-manager.ts
  src/providers/add-list-provider.ts
  src/providers/copilot-webview.ts
  src/providers/profile-list-provider.ts
  src/secret-storage-profile-manager.ts
  src/utils-api.ts
  src/utils.ts
  src/utils/ui-utils.ts
  src/workspace-manager.ts
  tsconfig.json
  webview/index.html
  webview/js/libs/index.6eb738df926bb986db0d.js
  webview/js/libs/index.6eb738df926bb986db0d.js.LICENSE.txt
  webview/js/main.6eb738df926bb986db0d.js
  webview/js/main.ecc57c8ece39b7e684b5.js
  webview/js/runtime.6eb738df926bb986db0d.js
  webview/styles/main.6eb738df926bb986db0d.css
  webview/styles/main.ecc57c8ece39b7e684b5.css
Labels: OCA Verified

#40 Feature/plan oic 56394 show server error
  package-lock.json
  package.json
  src/api.ts
  src/logger.ts
Labels: OCA Verified

#42 Feature/plan oic 56398 openapi path selector
  package.json
  schemas/flows_v01.json
  src/api.ts
  src/commands/convert-add.ts
  src/commands/convert-openapi-document.ts
  src/commands/convert-postman-collection.ts
  src/extension.ts
  src/logger.ts
  src/providers/copilot-webview.ts
  src/utils-api.ts
  src/utils.ts
  src/webview-shared-lib.ts
  webview/index.html
  webview/js/libs/index.0d0deb30a3db406d6c79.js
  webview/js/libs/index.0d0deb30a3db406d6c79.js.LICENSE.txt
  webview/js/libs/index.6eb738df926bb986db0d.js
  webview/js/main.0d0deb30a3db406d6c79.js
  webview/js/main.6eb738df926bb986db0d.js
  webview/js/runtime.0d0deb30a3db406d6c79.js
  webview/js/runtime.6eb738df926bb986db0d.js
  webview/styles/main.0d0deb30a3db406d6c79.css
  webview/styles/main.6eb738df926bb986db0d.css
Labels: OCA Verified, increment minor version, OIC24.06
